[2023-06-15T14:59:58.191+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.build_rst manual__2023-06-15T07:59:30+00:00 [queued]>
[2023-06-15T14:59:58.196+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.build_rst manual__2023-06-15T07:59:30+00:00 [queued]>
[2023-06-15T14:59:58.196+0700] {taskinstance.py:1308} INFO - Starting attempt 1 of 0
[2023-06-15T14:59:58.208+0700] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): build_rst> on 2023-06-15 07:59:30+00:00
[2023-06-15T14:59:58.210+0700] {standard_task_runner.py:57} INFO - Started process 33154 to run task
[2023-06-15T14:59:58.216+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'thethree_reqif_to_rst', 'build_rst', 'manual__2023-06-15T07:59:30+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/mainflow.py', '--cfg-path', '/var/folders/v7/qsb_cvl92z92z6jf7g1jc0zr0000gn/T/tmpw0x6qjmx']
[2023-06-15T14:59:58.218+0700] {standard_task_runner.py:85} INFO - Job 52: Subtask build_rst
[2023-06-15T14:59:58.269+0700] {task_command.py:410} INFO - Running <TaskInstance: thethree_reqif_to_rst.build_rst manual__2023-06-15T07:59:30+00:00 [running]> on host macbook-pro.local
[2023-06-15T14:59:58.309+0700] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='The Three' AIRFLOW_CTX_DAG_ID='thethree_reqif_to_rst' AIRFLOW_CTX_TASK_ID='build_rst' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T07:59:30+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T07:59:30+00:00'
[2023-06-15T14:59:58.315+0700] {mainflow.py:35} INFO - Loading config from /Users/lap14202/.airflow/data/config.yml
[2023-06-15T14:59:58.323+0700] {mainflow.py:37} INFO - Building rst...
[2023-06-15T14:59:58.323+0700] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lap14202/.airflow/dags/mainflow.py", line 38, in build_rst_task
    build_rst(json_data, config, 'rst_filepath')
  File "/Users/lap14202/.airflow/thethree/build_rst.py", line 100, in build_rst
    build_rst_artifacts(rst, artifacts, config["artifacts"]["artifact"])
  File "/Users/lap14202/.airflow/thethree/build_rst.py", line 77, in build_rst_artifacts
    rst_type = get_rst_type(artifact_type, rst_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lap14202/.airflow/thethree/build_rst.py", line 65, in get_rst_type
    if artifact_type == rst_config["heading"]["atifact_type"]:
                        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'atifact_type'
[2023-06-15T14:59:58.329+0700] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=thethree_reqif_to_rst, task_id=build_rst, execution_date=20230615T075930, start_date=20230615T075958, end_date=20230615T075958
[2023-06-15T14:59:58.335+0700] {standard_task_runner.py:104} ERROR - Failed to execute job 52 for task build_rst ('atifact_type'; 33154)
[2023-06-15T14:59:58.356+0700] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T14:59:58.372+0700] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
