[2023-06-15T20:06:55.128+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T13:06:32+00:00 [queued]>
[2023-06-15T20:06:55.132+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T13:06:32+00:00 [queued]>
[2023-06-15T20:06:55.133+0700] {taskinstance.py:1308} INFO - Starting attempt 1 of 0
[2023-06-15T20:06:55.141+0700] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_github> on 2023-06-15 13:06:32+00:00
[2023-06-15T20:06:55.144+0700] {standard_task_runner.py:57} INFO - Started process 68988 to run task
[2023-06-15T20:06:55.149+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'thethree_reqif_to_rst', 'upload_to_github', 'manual__2023-06-15T13:06:32+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/mainflow.py', '--cfg-path', '/var/folders/v7/qsb_cvl92z92z6jf7g1jc0zr0000gn/T/tmp17wtulva']
[2023-06-15T20:06:55.151+0700] {standard_task_runner.py:85} INFO - Job 82: Subtask upload_to_github
[2023-06-15T20:06:55.193+0700] {task_command.py:410} INFO - Running <TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T13:06:32+00:00 [running]> on host macbook-pro.local
[2023-06-15T20:06:55.236+0700] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='The Three' AIRFLOW_CTX_DAG_ID='thethree_reqif_to_rst' AIRFLOW_CTX_TASK_ID='upload_to_github' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T13:06:32+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T13:06:32+00:00'
[2023-06-15T20:08:10.623+0700] {local_task_job_runner.py:291} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2023-06-15T20:08:10.638+0700] {process_utils.py:131} INFO - Sending 15 to group 68988. PIDs of all processes in the group: [68988]
[2023-06-15T20:08:10.638+0700] {process_utils.py:86} INFO - Sending the signal 15 to group 68988
[2023-06-15T20:09:10.641+0700] {process_utils.py:149} WARNING - process psutil.Process(pid=68988, name='Python', status='running', started='20:06:55') did not respond to SIGTERM. Trying SIGKILL
[2023-06-15T20:09:10.642+0700] {process_utils.py:86} INFO - Sending the signal 9 to group 68988
[2023-06-15T20:09:10.658+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=68988, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='20:06:55') (68988) terminated with exit code -9
[2023-06-15T20:09:10.659+0700] {standard_task_runner.py:172} ERROR - Job 82 was killed before it finished (likely due to running out of memory)
