[2023-06-15T20:26:38.472+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T13:25:11+00:00 [queued]>
[2023-06-15T20:26:38.477+0700] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T13:25:11+00:00 [queued]>
[2023-06-15T20:26:38.478+0700] {taskinstance.py:1308} INFO - Starting attempt 1 of 0
[2023-06-15T20:26:38.489+0700] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_github> on 2023-06-15 13:25:11+00:00
[2023-06-15T20:26:38.491+0700] {standard_task_runner.py:57} INFO - Started process 72885 to run task
[2023-06-15T20:26:38.497+0700] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'thethree_reqif_to_rst', 'upload_to_github', 'manual__2023-06-15T13:25:11+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/mainflow.py', '--cfg-path', '/var/folders/v7/qsb_cvl92z92z6jf7g1jc0zr0000gn/T/tmp0rg6nnh0']
[2023-06-15T20:26:38.499+0700] {standard_task_runner.py:85} INFO - Job 96: Subtask upload_to_github
[2023-06-15T20:26:38.542+0700] {task_command.py:410} INFO - Running <TaskInstance: thethree_reqif_to_rst.upload_to_github manual__2023-06-15T13:25:11+00:00 [running]> on host macbook-pro.local
[2023-06-15T20:26:38.589+0700] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='The Three' AIRFLOW_CTX_DAG_ID='thethree_reqif_to_rst' AIRFLOW_CTX_TASK_ID='upload_to_github' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T13:25:11+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T13:25:11+00:00'
[2023-06-15T20:26:38.599+0700] {logging_mixin.py:149} INFO - {'AUTHENTICATION': {'TOKEN': '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', 'USERNAME': 'nxquang-al'}, 'MESSAGE': 'test-github-access-token', 'REPOSITORY': {'BRANCH': 'main', 'NAME': 'Test-github-api', 'OWNER': 'R2th'}} /Users/lap14202/.airflow/data/Requirements.rst
[2023-06-15T20:28:09.046+0700] {local_task_job_runner.py:291} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-06-15T20:28:09.071+0700] {process_utils.py:131} INFO - Sending 15 to group 72885. PIDs of all processes in the group: [72885]
[2023-06-15T20:28:09.072+0700] {process_utils.py:86} INFO - Sending the signal 15 to group 72885
[2023-06-15T20:29:09.078+0700] {process_utils.py:149} WARNING - process psutil.Process(pid=72885, name='Python', status='running', started='20:26:38') did not respond to SIGTERM. Trying SIGKILL
[2023-06-15T20:29:09.080+0700] {process_utils.py:86} INFO - Sending the signal 9 to group 72885
[2023-06-15T20:29:09.100+0700] {process_utils.py:79} INFO - Process psutil.Process(pid=72885, name='Python', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='20:26:38') (72885) terminated with exit code -9
[2023-06-15T20:29:09.102+0700] {standard_task_runner.py:172} ERROR - Job 96 was killed before it finished (likely due to running out of memory)
